apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: nginxinc/nginx-unprivileged
    newTag: "1.27.3"
replicas:
  - name: myapp
    count: 1
